# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: https://yhb-flydream.github.io/
url: https://yhb-flydream.github.io/  # http://mazhuang.org
date_format: "ordinal"
title: yhb-flydream
subtitle: 学习是一条令人时而欣喜若狂、时而郁郁寡欢的旅途。I Want Something Just Like This.
description: yhb-flydream, javascript, html, css, SEO, mip
keywords: yhb-flydream, javascript, html, css, SEO, mip
favicon: /favicon.ico
timezone: China/Zhengzhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: yhb-flydream
organization: E-commerce, Relational map, AI.
organization_url: https://www.linkeddb.com/
github_username: yhb-flydream
location: Zhengzhou, China
email: yhbflydream@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 收藏

  -
    href: /about/
    label: 关于

#  -
#    href: /me/
#    label: 简历

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: yhb-flydream.github.io/  # wenfengtou/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
disqus_username: mzlogin
netease_gentie_key: 560ed243b708465d82d5a0a5f3b83da1
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
